### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by AkashSrinivasan12** [INFO-526-S24/project-final-PlotWizards#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Abhishek Kumar, MS in Data Science - @ Abhi291712
- Noureen Mithaigar, MS in information science - @musketer26
- Akash Srinivasan, MS in Data Science - @AkashSrinivasan12
- Lakshmi Neharika Anchula, MS in Data Science - @ lakshmineharika
- Gowtham Theeda, MS in Data Science - @ gowthamtheeda
- Divya Liladhar Dhole, MS in Data Science - @Divyadhole

- Describe the goal of the project.

The main goal is to create a dashboard of a live, ongoing cricket match that updates its plots at regular, automatic intervals.

- Describe the data used or collected.

The ODI_Match_Data.csv: It provides facts about the location and season of the cricket matches. It looks like large dataset with more columns probably used GIT LFS LARGE FILE STORAGE. 
ODI_Match_info.csv: It overlaps in data with the above but provides information on the umpire, performance, and the city the match. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

They need to answer them including variables, plot representations, and insights that can be extracted from the visuals. 
 The first obstacle is to find the required field from the data, Scorecard summary, Batting Performance, Bowler’s economy rates as per the report. Different variables are used efficiently in-order to get the necessary output. 
The insights they mentioned were, Visualize the scoring rate throughout the innings, show periods of acceleration or deceleration in runs scored.
Plot Representation: Line chart or bar chart, Bar chart or stacked bar chart, Box plot or violin plot 

- Is there anything that is unclear from the proposal?

The Live dashboard is amazing, It will make it more interesting if the technique or method for doing it is mentioned in the proposal.
Author Description is not formatted properly, Its overlapping the side headings. 
It would be better if we can see or access the dataset link, so that we can try to figure out the insight beyond the purpose. 
Since dataset link is not there , It would be sufficient if  the important columns in the dataset and the datatypes of the columns are given in the output code pane or any where in the proposal.
EDA or pre-processing method or steps will add more insight information to the process and to the project.
Since there are two datasets it will be good if we can see what dataset  they are using for each questions, so that we can get the enough information to avoid unnecessary doubts.    
Some Alignments are good but not great under the research question.

- Provide constructive feedback on how the team might be able to improve their project.

Some alignments were not so good, The vision of the project is amazing but some technique are  unclear and missing in the proposal which add more value to the problem statement.
 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The interesting part is to see how they interlink the 2 datasets. 
And the live time updates of its plots at regular, automatic intervals that too on the dashboard, makes it more interesting.

- Provide constructive feedback on any issues with file and/or code organization.

The file organization is overall good, in someplace for example Dataset link, techniques, alignments  were missing. Adding the gist about the Dashboard or Technology behind the Dashboard will add more value and support to the proposal.  

- (Optional) Any further comments or feedback?

**Comment by poonkundransrinivasan** [comment]
Thankyou. You feedback was valuable. We have worked on the issues and updated it. One of the issues that we are facing the size of csv file that comes around 200MB and therefore cannot be uploaded in github. To resolve this, we are converting the entire csv file to a .db and only the needed and relevant data for an output will be sent by the backend.
