### ISSUE TITLE
Proposal peer review from GraphGeeks

### ISSUE THREAD

**Issue by vemuladevendran** [INFO-526-S24/project-final-PlotWizards#2]
The following is the peer review of the project proposal by GraphGeeks. The team members that participated in this review are 

- [Devendran Vemula] - @vemuladevendran
- [Gorantla Sai Laasya] - @Sailaasya-1
- [Mrunali Yadav ] - @mrunaliyadavps

### Describe the goal of the project.
The project aims to create a dynamic dashboard that simulates a live cricket match using historical data, updating plots at regular intervals to mimic real-time match progression.

### Describe the data used or collected.
The team intends to use two datasets as per the proposal: `ODI_Match_Data.csv` and `ODI_Match_info.csv`. However, only `ODI_Match_info.csv` is available in the data folder. The absence of `ODI_Match_Data.csv` and its mention in the README file might lead to confusion and needs clarification or rectification to align the project's documentation with its actual data resources.

### Describe how the research question will be answered, e.g., what approaches/methods will be used.
The team plans to utilize a variety of data visualization techniques, such as line charts, bar charts, box plots, and network graphs, to analyze different aspects of cricket matches. The proposed method of simulating a live match using historical data is innovative, and detailing the process would enhance the proposal's clarity.

### Is there anything that is unclear from the proposal?
- The mechanism for simulating "live" data from historical datasets could be more explicitly described.
- How the various visualizations will interact and form a unified dashboard is not fully clear and could be detailed further.

### Provide constructive feedback on how the team might be able to improve their project.
- Enhancing user interactivity within the dashboard would significantly improve its utility and user engagement.
- Clarifying the selection and purpose of each visualization type will provide a deeper understanding of the design choices.
- Addressing the discrepancy between the dataset descriptions in the README file and the actual datasets available would ensure consistency and clarity.

### What aspect of this project are you most interested in and would like to see highlighted in the presentation?
The method of simulating live match conditions using historical data is particularly interesting. Highlighting this process and its ability to provide real-time analytics would be a compelling feature of the presentation.

### Provide constructive feedback on any issues with file and/or code organization.
- Ensuring that the data folder contents match the project documentation will aid in maintaining the integrity and credibility of the analysis.

### (Optional) Any further comments or feedback?
The project presents an exciting approach to sports data analysis. Clarifying the dataset availability and enhancing the dashboard's interactivity could make this project a valuable tool for cricket enthusiasts and analysts alike. We look forward to seeing the final implementation and the insights it will provide into cricket dynamics.

**Comment by poonkundransrinivasan** [comment]
Thank you for the Informative feedback. We have added more detailed explanation on how we will mock the like data. 

The data in the README.md and the features in the actual proposal are different as the README has all the features and the proposal has only the features that we found to be relevant for the project.
