### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by zandi-omid** [INFO-526-S24/project-final-PlotWizards#5]
The following is the peer review of the Presentation proposal by GraphGeeks. The team members that participated in this review are 

[Devendran Vemula] - @vemuladevendran

[Gorantla Sai Laasya] - @Sailaasya-1

[Omid Zandi ] - @zandi-omid

[Gowtham Gopalakrishnan] - @Gowtham-18

[Rajitha Reddy] - @RAJITHAREDDYTIRUTHANI

[Mrunali Yadav ] - @mrunaliyadavps

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research question is articulated and aligns well with the study's overarching goal, making it a robust foundation for inquiry. The data used is pertinent and sufficiently comprehensive to address the research question.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Visual aids like charts and graphs are well-selected, contributing to the understanding of complex datasets. Each visualization is accompanied by an explanation that clarifies the relevance and implications of the data presented. However, the last panel of the Shiny app doesn't work. Also, they could have chosen more complicated types of visualizations, and the world map of the team performance panel on shiny app could have been interactive.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

It reflects a good level of creativity and critical analysis. There is a clear demonstration of effort in both the planning and execution stages. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well-structured, with a good balance between text and visuals which facilitates easy digestion of the content. The design is professional, and the use of colors and fonts enhances readability. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The presentation was executed with a high degree of professionalism. The team members were well-prepared, which was evident in their confident delivery and the smooth flow of the presentation.

**Comment by poonkundransrinivasan** [comment]
Thankyou for the valuable feedback. The last tab of the shiny server is completely based on the backend. As this server was running in our local computer, we couldn't have  kept the backend server running.
