### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Abhi291712** [INFO-526-S24/project-final-PlotWizards#6]
The following is the peer review of the Presentation proposal by Datavista. The team members that participated in this review are 

[AkashSrinivasan]-@AkashSrinivasan12

[ABHISHEK KUMAR]-@Abhi291712

[lakshmineharika]-@lakshmineharika

[Divyadhole]-@Divyadhole

[Noureen Mithaigar]-@musketer26

[gowthamtheeda]-@gowthamtheeda

- Content: Is the research question well designed and is the data being used relevant to the research question?
                *Yes, the questions were well-designed, and the data used was relevant to the research question.*

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
                 *yes they used appropriate visualizations and  interpret them accurately*

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time 
and effort went into the planning and implementation of the project?
               *They planned the project well, using API calls to obtain live data statistics. Although there may have been limitations as 
                 mentioned in the Presentation , their approach was out of the box*

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
                 *Yes, they used figures where needed. Slides were  organised.*

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
                   *The team presented well. Yes, the presentation seemed to be practiced. Everyone said meaningful things about the 
                     project*

**Comment by poonkundransrinivasan** [comment]
Thankyou for the feedback!!
